const { Client } = require('pg');

const client = new Client({
    host: 'db.jwkdxygcpfdmavxcbcfe.supabase.co',
    port: 5432,
    database: 'postgres',
    user: 'postgres',
    password: 'AISapience111$',
    ssl: { rejectUnauthorized: false },
});

const sql = `
-- 1. companies 테이블 생성
create table if not exists companies (
  id bigint generated by default as identity primary key,
  name_ko text not null,
  name_en text not null,
  status text not null, -- 'KOSPI', 'KOSDAQ', 'Unlisted', 'Global_Listed', 'Global_Private'
  category text not null, -- 'korean', 'global'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. 누구나 읽을 수 있도록 권한 설정 (RLS)
alter table companies enable row level security;

-- Drop existing policy if any (to avoid error)
do $$ begin
  drop policy "Enable read access for all users" on companies;
exception when undefined_object then end $$;

create policy "Enable read access for all users"
on companies for select
using (true);

-- 3. 기존 데이터 입력 (기본값)
-- Check if data exists first to avoid duplicates
insert into companies (id, name_ko, name_en, status, category)
select d.id, d.name_ko, d.name_en, d.status, d.category
from (
  values
  (1, '한스바이오메드', 'HansBiomed', 'KOSDAQ', 'korean'),
  (2, '엘앤씨바이오', 'L&C Bio', 'KOSDAQ', 'korean'),
  (3, '제테마', 'Jetema', 'KOSDAQ', 'korean'),
  (4, '한국비엔씨', 'BNC Korea', 'KOSDAQ', 'korean'),
  (5, '종근당바이오', 'Chong Kun Dang Bio', 'KOSPI', 'korean'),
  (6, '휴온스', 'Huons', 'KOSDAQ', 'korean'),
  (7, '휴온스글로벌', 'Huons Global', 'KOSDAQ', 'korean'),
  (8, '휴메딕스', 'Humedix', 'KOSDAQ', 'korean'),
  (9, '휴젤', 'Hugel', 'KOSDAQ', 'korean'),
  (10, '메디톡스', 'Medytox', 'KOSDAQ', 'korean'),
  (11, '대웅제약', 'Daewoong Pharma', 'KOSPI', 'korean'),
  (12, '파마리서치', 'PharmaResearch', 'KOSDAQ', 'korean'),
  (13, '클래시스', 'Classys', 'KOSDAQ', 'korean'),
  (14, '케어젠', 'Caregen', 'KOSDAQ', 'korean'),
  (15, '원텍', 'Wontech', 'KOSDAQ', 'korean'),
  (16, '동방메디컬', 'Dongbang Medical', 'KOSDAQ', 'korean'),
  (17, '제이시스메디칼', 'Jeisys Medical', 'Unlisted', 'korean'),
  (18, '바이오비쥬', 'BioBijou', 'KOSDAQ', 'korean'),
  (19, '바이오플러스', 'BioPlus', 'KOSDAQ', 'korean'),
  (20, '비올', 'Viol', 'KOSDAQ', 'korean'),
  (21, '하이로닉', 'Hironic', 'KOSDAQ', 'korean'),
  (22, '레이저옵텍', 'Laseroptek', 'KOSDAQ', 'korean'),
  (23, '유바이오로직스', 'EuBiologics', 'KOSDAQ', 'korean'),
  (24, '바임글로벌', 'Vaim Global', 'Unlisted', 'korean'),
  (25, '엑소코바이오', 'ExoCoBio', 'Unlisted', 'korean'),
  (26, '알에프바이오', 'RFBio', 'Unlisted', 'korean'),
  (27, '차메디텍', 'Cha Meditech', 'Unlisted', 'korean'),
  (28, 'JW중외제약', 'JW Pharmaceutical', 'KOSPI', 'korean'),
  (29, '동국제약', 'Dongkook Pharmaceutical', 'KOSDAQ', 'korean'),
  (30, '리젠바이오텍', 'Regen Biotech', 'Unlisted', 'korean'),
  (31, '울트라브이', 'Ultra V', 'Unlisted', 'korean'),
  (32, '제노스', 'Genoss', 'Unlisted', 'korean'),
  (33, '멀츠', 'Merz Aesthetics', 'Global_Private', 'global'),
  (34, '앨러간', 'Allergan Aesthetics', 'Global_Listed', 'global'),
  (35, '갈더마', 'Galderma', 'Global_Listed', 'global'),
  (36, '테옥산', 'Teoxane', 'Global_Private', 'global')
) as d(id, name_ko, name_en, status, category)
where not exists (
  select 1 from companies c where c.name_ko = d.name_ko
);

-- 4. ID 시퀀스 동기화
SELECT setval('companies_id_seq', (SELECT MAX(id) FROM companies));
`;

async function main() {
    try {
        await client.connect();
        console.log('Connected to DB');
        await client.query(sql);
        console.log('Successfully executed SQL!');
    } catch (err) {
        console.error('Error executing SQL', err);
    } finally {
        await client.end();
    }
}

main();
