-- Migration: Add financials and reports tables, and populate data

-- 1. Add columns to companies
ALTER TABLE companies ADD COLUMN IF NOT EXISTS stock_code text;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS logo_url text;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS website_url text;

-- 2. Create financials table
CREATE TABLE IF NOT EXISTS financials (
  id bigint generated by default as identity primary key,
  company_id bigint references companies(id) not null,
  year int not null,
  revenue bigint,
  operating_profit bigint,
  rd_cost text, -- Keeping as text for 'N/A' or mixed values if needed, or stick to structure
  data_type text, -- 'annual', 'annual_naver', etc.
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint unique_financial_year unique (company_id, year)
);

-- 3. Create reports table
CREATE TABLE IF NOT EXISTS reports (
  id bigint generated by default as identity primary key,
  company_id bigint references companies(id) not null,
  year int not null,
  period text not null, -- 'annual', '1Q', '2Q', '3Q', '4Q'
  title text not null,
  url text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Enable RLS
ALTER TABLE financials ENABLE ROW LEVEL SECURITY;
ALTER TABLE reports ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  DROP POLICY "Enable read for all" ON financials;
EXCEPTION WHEN undefined_object THEN END $$;
CREATE POLICY "Enable read for all" ON financials FOR SELECT USING (true);

DO $$ BEGIN
  DROP POLICY "Enable read for all" ON reports;
EXCEPTION WHEN undefined_object THEN END $$;
CREATE POLICY "Enable read for all" ON reports FOR SELECT USING (true);

-- 5. Data Migration

-- Update Companies
UPDATE companies SET stock_code = '042520', description = '유방 보형물 ''벨라젤''과 리프팅 실 브랜드 ''민트리프트(MINT Lift)''를 생산합니다. 뼈 이식재 등 인체조직 재생 제품과 미용 성형용 소모품을 공급하고 있습니다.' WHERE id = 1;
UPDATE companies SET stock_code = '290650', description = '인체조직 이식재 ''메가덤''과 무릎 연골 재생 치료제 ''메가카티''를 제조하여 공급합니다. 피부 재생 스킨부스터 ''리투오'' 등 재생 의학 기반의 제품군을 보유하고 있습니다.' WHERE id = 2;
UPDATE companies SET stock_code = '216080', description = NULL WHERE id = 3;
UPDATE companies SET stock_code = '256840', description = '히알루론산 필러 브랜드 ''테소로(Tesoro)''와 전문 의약품용 유착방지제를 제조합니다. 생체 재료 기반 의료기기 생산과 더불어 신약 파이프라인 연구개발을 수행합니다.' WHERE id = 4;
UPDATE companies SET stock_code = '063160', description = '보툴리눔 톡신 제제 ''티엠버스(Tyemvers)''와 항생제 원료의약품을 생산합니다. 프로바이오틱스 원료 공급과 더불어 차세대 톡신 및 마이크로바이옴 연구를 수행합니다.' WHERE id = 5;
UPDATE companies SET stock_code = '243070', description = '보툴리눔 톡신 ''리즈톡스''의 국내 유통과 국소마취제 ''리도카인'' 생산을 담당합니다. 전문의약품 및 수액제, 웰빙 의약품군을 생산하는 종합 제약 기업입니다.' WHERE id = 6;
UPDATE companies SET stock_code = '084110', description = NULL WHERE id = 7;
UPDATE companies SET stock_code = '200670', description = '히알루론산 필러 브랜드 ''엘라비에(Elravie)''와 관절염 치료제 ''하이히알'' 등을 생산합니다. 원료의약품 제조 기술을 바탕으로 필러 및 기능성 화장품 사업을 영위합니다.' WHERE id = 8;
UPDATE companies SET stock_code = '145020', description = NULL WHERE id = 9;
UPDATE companies SET stock_code = '086900', description = '보툴리눔 톡신 제제 ''메디톡신''과 히알루론산 필러 ''뉴라미스''를 주력으로 생산합니다. ''코어톡스'' 등 신규 톡신 제제 라인업을 통해 에스테틱 사업을 영위하고 있습니다.' WHERE id = 10;
UPDATE companies SET stock_code = '069620', description = NULL WHERE id = 11;
UPDATE companies SET stock_code = '214450', description = '연어 유래 성분의 스킨부스터 ''리쥬란(REJURAN)''과 관절강 주사 ''콘쥬란''을 제조합니다. PDRN/PN 원천 기술을 기반으로 의약품과 의료기기 사업을 운영하고 있습니다.' WHERE id = 12;
UPDATE companies SET stock_code = '214150', description = NULL WHERE id = 13;
UPDATE companies SET stock_code = '214370', description = '펩타이드 필러 ''레보필(REVOFIL)''과 기능성 화장품 브랜드 ''더마힐''을 제조합니다. 펩타이드 플랫폼 기술을 활용하여 필러 및 건강기능식품 사업을 영위합니다.' WHERE id = 14;
UPDATE companies SET stock_code = '336570', description = NULL WHERE id = 15;
UPDATE companies SET stock_code = '240550', description = NULL WHERE id = 16;
UPDATE companies SET stock_code = '287410', description = '고주파 미용 기기 ''포텐자(POTENZA)''와 초음파 장비 ''리니어지(LinearZ)''를 설계 및 제조합니다. 글로벌 유통망을 통해 미용 성형용 에너지 의료기기를 수출하고 있습니다.' WHERE id = 17;
UPDATE companies SET stock_code = '489460', description = NULL WHERE id = 18;
UPDATE companies SET stock_code = '099430', description = '히알루론산 필러 ''하이알듀(HyalDew)''와 유착방지제를 생산합니다. 생체 재료 기술을 기반으로 미용 성형용 의료기기와 유착방지 제품을 제조합니다.' WHERE id = 19;
UPDATE companies SET stock_code = '335890', description = NULL WHERE id = 20;
UPDATE companies SET stock_code = '149980', description = NULL WHERE id = 21;
UPDATE companies SET stock_code = '199550', description = '피부 질환 및 미용 치료용 레이저 기기인 ''팔라스(PALLAS)''와 ''헬리오스(HELIOS)'' 시리즈를 제조합니다. 독자적인 레이저 설계 기술을 바탕으로 의료용 장비 사업을 운영합니다.' WHERE id = 22;
UPDATE companies SET stock_code = '206650', description = '경구용 콜레라 백신 ''유비콜(Euvichol)''을 생산하여 글로벌 공공 시장에 공급합니다. 백신 제조 기술을 바탕으로 바이오의약품 위탁생산(CMO) 서비스를 제공합니다.' WHERE id = 23;
UPDATE companies SET stock_code = '001060', description = NULL WHERE id = 28;
UPDATE companies SET stock_code = '086450', description = NULL WHERE id = 29;

-- Insert Financials

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (1, 2022, 20214623244, 1298028272, '-', 'annual')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (1, 2023, 18466892403, 121738664, '-', 'annual')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (1, 2024, 20814468108, 653951434, '-', 'annual')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (1, 2025, 22033892083, 40796559, '-', 'annual')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (2, 2022, 52600000000, 9500000000, '-', 'annual_naver')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (2, 2023, 68869546328, 7748005680, '-', 'annual')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (2, 2024, 72093323401, 2542071249, '-', 'annual')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (2, 2025, 88600000000, 6200000000, '-', 'estimated_naver')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (3, 2022, 46000000000, 4000000000, '-', 'annual_naver')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (3, 2023, 58700000000, 2600000000, '-', 'annual_naver')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (3, 2024, 68520182954, 4110925721, '-', 'annual')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (4, 2022, 42303378385, -10096839835, '-', 'annual')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (4, 2023, 80997489681, 6045988919, '-', 'annual')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (4, 2024, 89229997633, 10705760232, '-', 'annual')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (5, 2021, 142238418404, -11432270296, '-', 'annual')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (5, 2022, 156042327041, -14810343537, '-', 'annual')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (5, 2023, 160352778354, -20152520381, '-', 'annual')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (5, 2024, 171756008722, 10953544485, '-', 'annual')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (6, 2022, 492400000000, 40900000000, '-', 'annual_naver')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (6, 2023, 552006502264, 56002319215, '-', 'annual')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (6, 2024, 590231059719, 39695088137, '-', 'annual')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (6, 2025, 614200000000, 46100000000, '-', 'estimated_naver')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (7, 2022, 664400000000, 86500000000, '-', 'annual_naver')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (7, 2023, 758400000000, 114000000000, '-', 'annual_naver')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (7, 2024, 813500000000, 97000000000, '-', 'annual_naver')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (8, 2022, 123200000000, 26000000000, '-', 'annual_naver')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (8, 2023, 152273808567, 37310070521, '-', 'annual')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (8, 2024, 161872958430, 43141324184, '-', 'annual')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (8, 2025, 170300000000, 41900000000, '-', 'estimated_naver')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (9, 2022, 281700000000, 101400000000, '-', 'annual_naver')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (9, 2023, 319700000000, 117800000000, '-', 'annual_naver')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (9, 2024, 373046885998, 166229170618, '-', 'annual')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (9, 2025, 419700000000, 195000000000, '-', 'estimated_naver')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (10, 2022, 195100000000, 46700000000, '-', 'annual_naver')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (10, 2023, 221120682597, 17322328805, '-', 'annual')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (10, 2024, 228621969000, 20348723000, '-', 'annual')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (10, 2025, 253600000000, 30200000000, '-', 'estimated_naver')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (11, 2022, 1280100000000, 95800000000, '-', 'annual_naver')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (11, 2023, 1375300000000, 122600000000, '-', 'annual_naver')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (11, 2024, 1422683296380, 147942198476, '-', 'annual')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (11, 2025, 1579900000000, 200300000000, '-', 'estimated_naver')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (12, 2022, 194800000000, 65900000000, '-', 'annual_naver')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (12, 2023, 261010910564, 92257786628, '-', 'annual')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (12, 2024, 350115068641, 126050757121, '-', 'annual')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (12, 2025, 547500000000, 228100000000, '-', 'estimated_naver')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (13, 2022, 141800000000, 68900000000, '-', 'annual_naver')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (13, 2023, 180100000000, 89600000000, '-', 'annual_naver')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (13, 2024, 242900000000, 122400000000, '-', 'annual_naver')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (13, 2025, 341200000000, 167900000000, '-', 'estimated_naver')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (14, 2022, 69100000000, 33600000000, '-', 'annual_naver')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (14, 2023, 79209511675, 40377972813, '-', 'annual')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (14, 2024, 82585947786, 34249787129, '-', 'annual')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (16, 2022, 77300000000, 5500000000, '-', 'annual_naver')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (16, 2023, 90900000000, 16500000000, '-', 'annual_naver')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (16, 2024, 105113645139, 15045956736, '-', 'annual')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (16, 2025, 115200000000, 16600000000, '-', 'estimated_naver')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (17, 2023, 143029552904, 36313752059, '-', 'annual')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (17, 2024, 192076238234, 39973819896, '-', 'annual')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (18, 2022, 21100000000, 3600000000, '-', 'annual_naver')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (18, 2023, 17100000000, 5200000000, '-', 'annual_naver')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (18, 2024, 29600000000, 9200000000, '-', 'annual_naver')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (19, 2022, 56718818557, 25271435156, '-', 'annual')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (19, 2023, 65042901061, 28025617245, '-', 'annual')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (19, 2024, 66409594582, 23667463055, '-', 'annual')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (20, 2024, 58193098799, 36061882438, '-', 'annual')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (21, 2022, 27600000000, 3600000000, '-', 'annual_naver')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (21, 2023, 33700000000, 5300000000, '-', 'annual_naver')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (21, 2024, 31628770815, -4757481207, '-', 'annual')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (22, 2022, 30000000000, 2500000000, '-', 'annual_naver')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (22, 2023, 34352053954, 4480826362, '-', 'annual')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (22, 2024, 33037915734, -196045064, '-', 'annual')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (23, 2022, 55500000000, -3800000000, '-', 'annual_naver')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (23, 2023, 69365660612, 7699109509, '-', 'annual')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (23, 2024, 96035297831, 34321335803, '-', 'annual')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (23, 2025, 156400000000, 60200000000, '-', 'estimated_naver')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (24, 2022, 14070000000, NULL, 'N/A', 'manual')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (24, 2023, 28730000000, NULL, 'N/A', 'manual')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (33, 2023, 1012500000000, NULL, 'N/A', 'manual')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (34, 2023, 7155000000000, NULL, 'N/A', 'manual')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (35, 2023, 5510700000000, NULL, 'N/A', 'manual')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (36, 2023, 367200000000, NULL, 'N/A', 'manual')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (27, 2022, 11400000000, NULL, 'N/A', 'manual')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (28, 2022, 684400000000, 63000000000, '-', 'annual_naver')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (28, 2023, 748526707817, 100303770111, '-', 'annual')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (28, 2024, 719375756340, 82488136816, '-', 'annual')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (29, 2022, 661600000000, 73900000000, '-', 'annual_naver')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (29, 2023, 731000000000, 66900000000, '-', 'annual_naver')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (29, 2024, 812200000000, 80400000000, '-', 'annual_naver')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (29, 2025, 917200000000, 97000000000, '-', 'estimated_naver')
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          

-- Insert Reports
-- For reports, we don't have a unique constraint easily (title/url duplicates?), so we might delete existing first for Idempotency
DELETE FROM reports;
INSERT INTO reports (company_id, year, period, title, url) VALUES (1, 2022, 'annual', '사업보고서 (2022.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20221220000196');
INSERT INTO reports (company_id, year, period, title, url) VALUES (1, 2022, 'Q4', '분기보고서 (2022.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20230214001079');
INSERT INTO reports (company_id, year, period, title, url) VALUES (1, 2023, 'annual', '사업보고서 (2023.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20231219000383');
INSERT INTO reports (company_id, year, period, title, url) VALUES (1, 2023, 'Q2', '분기보고서 (2023.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20230814001141');
INSERT INTO reports (company_id, year, period, title, url) VALUES (1, 2023, 'Q4', '[기재정정]분기보고서 (2023.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240215000279');
INSERT INTO reports (company_id, year, period, title, url) VALUES (1, 2024, 'annual', '사업보고서 (2024.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20241219000524');
INSERT INTO reports (company_id, year, period, title, url) VALUES (1, 2024, 'Q2', '분기보고서 (2024.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240814001376');
INSERT INTO reports (company_id, year, period, title, url) VALUES (1, 2024, 'Q4', '분기보고서 (2024.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250214002522');
INSERT INTO reports (company_id, year, period, title, url) VALUES (1, 2025, 'annual', '사업보고서 (2025.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20251218000494');
INSERT INTO reports (company_id, year, period, title, url) VALUES (1, 2025, 'Q2', '분기보고서 (2025.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250814003628');
INSERT INTO reports (company_id, year, period, title, url) VALUES (2, 2023, 'annual', '사업보고서 (2023.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240320001633');
INSERT INTO reports (company_id, year, period, title, url) VALUES (2, 2024, 'annual', '사업보고서 (2024.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250321001430');
INSERT INTO reports (company_id, year, period, title, url) VALUES (2, 2024, 'Q1', '분기보고서 (2024.03)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240516000903');
INSERT INTO reports (company_id, year, period, title, url) VALUES (2, 2024, 'Q2', '반기보고서 (2024.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240814004035');
INSERT INTO reports (company_id, year, period, title, url) VALUES (2, 2024, 'Q3', '분기보고서 (2024.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20241114002539');
INSERT INTO reports (company_id, year, period, title, url) VALUES (2, 2025, 'Q1', '분기보고서 (2025.03)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250515001978');
INSERT INTO reports (company_id, year, period, title, url) VALUES (2, 2025, 'Q2', '반기보고서 (2025.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250814003932');
INSERT INTO reports (company_id, year, period, title, url) VALUES (2, 2025, 'Q3', '분기보고서 (2025.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20251114002166');
INSERT INTO reports (company_id, year, period, title, url) VALUES (3, 2024, 'annual', '사업보고서 (2024.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250321000516');
INSERT INTO reports (company_id, year, period, title, url) VALUES (3, 2024, 'Q2', '반기보고서 (2024.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240813000680');
INSERT INTO reports (company_id, year, period, title, url) VALUES (3, 2024, 'Q3', '분기보고서 (2024.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20241114001303');
INSERT INTO reports (company_id, year, period, title, url) VALUES (3, 2025, 'Q1', '분기보고서 (2025.03)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250515002923');
INSERT INTO reports (company_id, year, period, title, url) VALUES (3, 2025, 'Q2', '반기보고서 (2025.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250814002921');
INSERT INTO reports (company_id, year, period, title, url) VALUES (3, 2025, 'Q3', '분기보고서 (2025.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20251114002486');
INSERT INTO reports (company_id, year, period, title, url) VALUES (4, 2022, 'annual', '[기재정정]사업보고서 (2022.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20231213000526');
INSERT INTO reports (company_id, year, period, title, url) VALUES (4, 2023, 'annual', '사업보고서 (2023.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240321001661');
INSERT INTO reports (company_id, year, period, title, url) VALUES (4, 2023, 'Q1', '[기재정정]분기보고서 (2023.03)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20230516000296');
INSERT INTO reports (company_id, year, period, title, url) VALUES (4, 2023, 'Q2', '반기보고서 (2023.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20230814001727');
INSERT INTO reports (company_id, year, period, title, url) VALUES (4, 2023, 'Q3', '[기재정정]분기보고서 (2023.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20231213000528');
INSERT INTO reports (company_id, year, period, title, url) VALUES (4, 2024, 'annual', '[기재정정]사업보고서 (2024.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250814003452');
INSERT INTO reports (company_id, year, period, title, url) VALUES (4, 2024, 'Q1', '분기보고서 (2024.03)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240516001689');
INSERT INTO reports (company_id, year, period, title, url) VALUES (4, 2024, 'Q2', '반기보고서 (2024.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240814004073');
INSERT INTO reports (company_id, year, period, title, url) VALUES (4, 2024, 'Q3', '분기보고서 (2024.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20241114002117');
INSERT INTO reports (company_id, year, period, title, url) VALUES (4, 2025, 'Q1', '분기보고서 (2025.03)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250515002448');
INSERT INTO reports (company_id, year, period, title, url) VALUES (4, 2025, 'Q2', '반기보고서 (2025.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250814003531');
INSERT INTO reports (company_id, year, period, title, url) VALUES (4, 2025, 'Q3', '분기보고서 (2025.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20251114002256');
INSERT INTO reports (company_id, year, period, title, url) VALUES (5, 2021, 'annual', '사업보고서 (2021.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20220317000204');
INSERT INTO reports (company_id, year, period, title, url) VALUES (5, 2021, 'Q1', '분기보고서 (2021.03)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20210517000035');
INSERT INTO reports (company_id, year, period, title, url) VALUES (5, 2021, 'Q2', '반기보고서 (2021.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20210817000677');
INSERT INTO reports (company_id, year, period, title, url) VALUES (5, 2021, 'Q3', '분기보고서 (2021.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20211115001780');
INSERT INTO reports (company_id, year, period, title, url) VALUES (5, 2022, 'annual', '사업보고서 (2022.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20230314000316');
INSERT INTO reports (company_id, year, period, title, url) VALUES (5, 2022, 'Q1', '분기보고서 (2022.03)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20220516000733');
INSERT INTO reports (company_id, year, period, title, url) VALUES (5, 2022, 'Q2', '반기보고서 (2022.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20220816001512');
INSERT INTO reports (company_id, year, period, title, url) VALUES (5, 2022, 'Q3', '분기보고서 (2022.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20221114001179');
INSERT INTO reports (company_id, year, period, title, url) VALUES (5, 2023, 'annual', '사업보고서 (2023.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240320001689');
INSERT INTO reports (company_id, year, period, title, url) VALUES (5, 2023, 'Q1', '분기보고서 (2023.03)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20230515001059');
INSERT INTO reports (company_id, year, period, title, url) VALUES (5, 2023, 'Q2', '반기보고서 (2023.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20230811001729');
INSERT INTO reports (company_id, year, period, title, url) VALUES (5, 2023, 'Q3', '분기보고서 (2023.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20231114001732');
INSERT INTO reports (company_id, year, period, title, url) VALUES (5, 2024, 'annual', '사업보고서 (2024.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250318001004');
INSERT INTO reports (company_id, year, period, title, url) VALUES (5, 2024, 'Q1', '분기보고서 (2024.03)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240516001395');
INSERT INTO reports (company_id, year, period, title, url) VALUES (5, 2024, 'Q2', '반기보고서 (2024.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240814003522');
INSERT INTO reports (company_id, year, period, title, url) VALUES (5, 2024, 'Q3', '분기보고서 (2024.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20241114001292');
INSERT INTO reports (company_id, year, period, title, url) VALUES (5, 2025, 'Q1', '분기보고서 (2025.03)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250515001546');
INSERT INTO reports (company_id, year, period, title, url) VALUES (5, 2025, 'Q2', '반기보고서 (2025.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250814003489');
INSERT INTO reports (company_id, year, period, title, url) VALUES (5, 2025, 'Q3', '분기보고서 (2025.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20251114002206');
INSERT INTO reports (company_id, year, period, title, url) VALUES (6, 2023, 'annual', '사업보고서 (2023.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240320000849');
INSERT INTO reports (company_id, year, period, title, url) VALUES (6, 2024, 'annual', '사업보고서 (2024.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250318000815');
INSERT INTO reports (company_id, year, period, title, url) VALUES (6, 2024, 'Q1', '분기보고서 (2024.03)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240516001590');
INSERT INTO reports (company_id, year, period, title, url) VALUES (6, 2024, 'Q2', '반기보고서 (2024.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240814001126');
INSERT INTO reports (company_id, year, period, title, url) VALUES (6, 2024, 'Q3', '분기보고서 (2024.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20241114002437');
INSERT INTO reports (company_id, year, period, title, url) VALUES (6, 2025, 'Q1', '분기보고서 (2025.03)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250515003027');
INSERT INTO reports (company_id, year, period, title, url) VALUES (6, 2025, 'Q2', '반기보고서 (2025.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250814003610');
INSERT INTO reports (company_id, year, period, title, url) VALUES (6, 2025, 'Q3', '분기보고서 (2025.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20251114002901');
INSERT INTO reports (company_id, year, period, title, url) VALUES (7, 2023, 'annual', '[기재정정]사업보고서 (2023.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240321001484');
INSERT INTO reports (company_id, year, period, title, url) VALUES (7, 2024, 'annual', '사업보고서 (2024.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250320001575');
INSERT INTO reports (company_id, year, period, title, url) VALUES (7, 2024, 'Q1', '분기보고서 (2024.03)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240516000140');
INSERT INTO reports (company_id, year, period, title, url) VALUES (7, 2024, 'Q2', '반기보고서 (2024.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240814001127');
INSERT INTO reports (company_id, year, period, title, url) VALUES (7, 2024, 'Q3', '분기보고서 (2024.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20241114000624');
INSERT INTO reports (company_id, year, period, title, url) VALUES (7, 2025, 'Q1', '분기보고서 (2025.03)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250515000869');
INSERT INTO reports (company_id, year, period, title, url) VALUES (7, 2025, 'Q2', '반기보고서 (2025.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250814003093');
INSERT INTO reports (company_id, year, period, title, url) VALUES (7, 2025, 'Q3', '[기재정정]분기보고서 (2025.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20251114003116');
INSERT INTO reports (company_id, year, period, title, url) VALUES (8, 2023, 'annual', '사업보고서 (2023.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240320000202');
INSERT INTO reports (company_id, year, period, title, url) VALUES (8, 2023, 'Q2', '반기보고서 (2023.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20230810000460');
INSERT INTO reports (company_id, year, period, title, url) VALUES (8, 2023, 'Q3', '분기보고서 (2023.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20231110000012');
INSERT INTO reports (company_id, year, period, title, url) VALUES (8, 2024, 'annual', '사업보고서 (2024.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250318000146');
INSERT INTO reports (company_id, year, period, title, url) VALUES (8, 2024, 'Q1', '분기보고서 (2024.03)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240510000129');
INSERT INTO reports (company_id, year, period, title, url) VALUES (8, 2024, 'Q2', '반기보고서 (2024.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240813000098');
INSERT INTO reports (company_id, year, period, title, url) VALUES (8, 2024, 'Q3', '분기보고서 (2024.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20241111000061');
INSERT INTO reports (company_id, year, period, title, url) VALUES (8, 2025, 'Q1', '분기보고서 (2025.03)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250515000188');
INSERT INTO reports (company_id, year, period, title, url) VALUES (8, 2025, 'Q2', '반기보고서 (2025.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250814001007');
INSERT INTO reports (company_id, year, period, title, url) VALUES (8, 2025, 'Q3', '분기보고서 (2025.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20251114000119');
INSERT INTO reports (company_id, year, period, title, url) VALUES (9, 2024, 'annual', '사업보고서 (2024.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250321000621');
INSERT INTO reports (company_id, year, period, title, url) VALUES (9, 2024, 'Q2', '반기보고서 (2024.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240814001396');
INSERT INTO reports (company_id, year, period, title, url) VALUES (9, 2024, 'Q3', '분기보고서 (2024.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20241114001233');
INSERT INTO reports (company_id, year, period, title, url) VALUES (9, 2025, 'Q1', '분기보고서 (2025.03)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250515002369');
INSERT INTO reports (company_id, year, period, title, url) VALUES (9, 2025, 'Q2', '반기보고서 (2025.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250814002269');
INSERT INTO reports (company_id, year, period, title, url) VALUES (9, 2025, 'Q3', '분기보고서 (2025.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20251114001274');
INSERT INTO reports (company_id, year, period, title, url) VALUES (10, 2023, 'annual', '사업보고서 (2023.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240321001302');
INSERT INTO reports (company_id, year, period, title, url) VALUES (10, 2023, 'Q3', '분기보고서 (2023.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20231113000743');
INSERT INTO reports (company_id, year, period, title, url) VALUES (10, 2024, 'annual', '사업보고서 (2024.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250320001592');
INSERT INTO reports (company_id, year, period, title, url) VALUES (10, 2024, 'Q1', '분기보고서 (2024.03)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240516001990');
INSERT INTO reports (company_id, year, period, title, url) VALUES (10, 2024, 'Q2', '반기보고서 (2024.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240814003759');
INSERT INTO reports (company_id, year, period, title, url) VALUES (10, 2024, 'Q3', '분기보고서 (2024.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20241114002330');
INSERT INTO reports (company_id, year, period, title, url) VALUES (10, 2025, 'Q1', '분기보고서 (2025.03)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250514001162');
INSERT INTO reports (company_id, year, period, title, url) VALUES (10, 2025, 'Q2', '반기보고서 (2025.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250814000625');
INSERT INTO reports (company_id, year, period, title, url) VALUES (10, 2025, 'Q3', '분기보고서 (2025.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20251113000758');
INSERT INTO reports (company_id, year, period, title, url) VALUES (11, 2023, 'annual', '사업보고서 (2023.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240320001120');
INSERT INTO reports (company_id, year, period, title, url) VALUES (11, 2024, 'annual', '[기재정정]사업보고서 (2024.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250814004375');
INSERT INTO reports (company_id, year, period, title, url) VALUES (11, 2024, 'Q1', '분기보고서 (2024.03)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240514001381');
INSERT INTO reports (company_id, year, period, title, url) VALUES (11, 2024, 'Q2', '반기보고서 (2024.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240814004326');
INSERT INTO reports (company_id, year, period, title, url) VALUES (11, 2024, 'Q3', '분기보고서 (2024.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20241114001604');
INSERT INTO reports (company_id, year, period, title, url) VALUES (11, 2025, 'Q1', '분기보고서 (2025.03)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250515002222');
INSERT INTO reports (company_id, year, period, title, url) VALUES (11, 2025, 'Q2', '반기보고서 (2025.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250814004456');
INSERT INTO reports (company_id, year, period, title, url) VALUES (11, 2025, 'Q3', '분기보고서 (2025.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20251114001339');
INSERT INTO reports (company_id, year, period, title, url) VALUES (12, 2023, 'annual', '사업보고서 (2023.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240315000795');
INSERT INTO reports (company_id, year, period, title, url) VALUES (12, 2023, 'Q3', '분기보고서 (2023.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20231114002119');
INSERT INTO reports (company_id, year, period, title, url) VALUES (12, 2024, 'annual', '사업보고서 (2024.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250317000758');
INSERT INTO reports (company_id, year, period, title, url) VALUES (12, 2024, 'Q1', '분기보고서 (2024.03)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240514001617');
INSERT INTO reports (company_id, year, period, title, url) VALUES (12, 2024, 'Q2', '반기보고서 (2024.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240814004016');
INSERT INTO reports (company_id, year, period, title, url) VALUES (12, 2024, 'Q3', '분기보고서 (2024.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20241113000721');
INSERT INTO reports (company_id, year, period, title, url) VALUES (12, 2025, 'Q1', '[기재정정]분기보고서 (2025.03)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250521000230');
INSERT INTO reports (company_id, year, period, title, url) VALUES (12, 2025, 'Q2', '반기보고서 (2025.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250814002565');
INSERT INTO reports (company_id, year, period, title, url) VALUES (12, 2025, 'Q3', '분기보고서 (2025.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20251114000932');
INSERT INTO reports (company_id, year, period, title, url) VALUES (13, 2024, 'annual', '사업보고서 (2024.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250321001623');
INSERT INTO reports (company_id, year, period, title, url) VALUES (13, 2024, 'Q2', '반기보고서 (2024.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240814003845');
INSERT INTO reports (company_id, year, period, title, url) VALUES (13, 2024, 'Q3', '분기보고서 (2024.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20241114001342');
INSERT INTO reports (company_id, year, period, title, url) VALUES (13, 2025, 'Q1', '분기보고서 (2025.03)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250515003058');
INSERT INTO reports (company_id, year, period, title, url) VALUES (13, 2025, 'Q2', '반기보고서 (2025.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250814004297');
INSERT INTO reports (company_id, year, period, title, url) VALUES (13, 2025, 'Q3', '분기보고서 (2025.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20251114002953');
INSERT INTO reports (company_id, year, period, title, url) VALUES (14, 2023, 'annual', '사업보고서 (2023.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240311000407');
INSERT INTO reports (company_id, year, period, title, url) VALUES (14, 2024, 'annual', '사업보고서 (2024.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250317000927');
INSERT INTO reports (company_id, year, period, title, url) VALUES (14, 2024, 'Q1', '분기보고서 (2024.03)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240513000430');
INSERT INTO reports (company_id, year, period, title, url) VALUES (14, 2024, 'Q2', '반기보고서 (2024.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240814002146');
INSERT INTO reports (company_id, year, period, title, url) VALUES (14, 2024, 'Q3', '분기보고서 (2024.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20241113000332');
INSERT INTO reports (company_id, year, period, title, url) VALUES (14, 2025, 'Q1', '분기보고서 (2025.03)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250513000540');
INSERT INTO reports (company_id, year, period, title, url) VALUES (14, 2025, 'Q2', '반기보고서 (2025.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250814003836');
INSERT INTO reports (company_id, year, period, title, url) VALUES (14, 2025, 'Q3', '분기보고서 (2025.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20251114000849');
INSERT INTO reports (company_id, year, period, title, url) VALUES (15, 2021, 'annual', '[기재정정]사업보고서 (2021.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20220721000157');
INSERT INTO reports (company_id, year, period, title, url) VALUES (16, 2021, 'annual', '감사보고서 (2021.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20220404003254');
INSERT INTO reports (company_id, year, period, title, url) VALUES (16, 2022, 'annual', '연결감사보고서 (2022.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20230427000615');
INSERT INTO reports (company_id, year, period, title, url) VALUES (16, 2023, 'annual', '연결감사보고서 (2023.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240329001613');
INSERT INTO reports (company_id, year, period, title, url) VALUES (16, 2024, 'annual', '사업보고서 (2024.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250320001252');
INSERT INTO reports (company_id, year, period, title, url) VALUES (16, 2025, 'Q1', '분기보고서 (2025.03)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250527000563');
INSERT INTO reports (company_id, year, period, title, url) VALUES (16, 2025, 'Q2', '반기보고서 (2025.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250827000578');
INSERT INTO reports (company_id, year, period, title, url) VALUES (16, 2025, 'Q3', '분기보고서 (2025.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20251125000378');
INSERT INTO reports (company_id, year, period, title, url) VALUES (17, 2023, 'annual', '사업보고서 (2023.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240314001085');
INSERT INTO reports (company_id, year, period, title, url) VALUES (17, 2023, 'Q3', '분기보고서 (2023.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20231109000100');
INSERT INTO reports (company_id, year, period, title, url) VALUES (17, 2024, 'annual', '사업보고서 (2024.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250407003477');
INSERT INTO reports (company_id, year, period, title, url) VALUES (17, 2024, 'Q1', '분기보고서 (2024.03)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240510000873');
INSERT INTO reports (company_id, year, period, title, url) VALUES (17, 2024, 'Q2', '반기보고서 (2024.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240814003970');
INSERT INTO reports (company_id, year, period, title, url) VALUES (17, 2024, 'Q3', '분기보고서 (2024.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20241114001304');
INSERT INTO reports (company_id, year, period, title, url) VALUES (18, 2022, 'annual', '[기재정정]감사보고서 (2022.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240813000430');
INSERT INTO reports (company_id, year, period, title, url) VALUES (18, 2023, 'annual', '[기재정정]감사보고서 (2023.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240813000437');
INSERT INTO reports (company_id, year, period, title, url) VALUES (18, 2024, 'annual', '[기재정정]연결감사보고서 (2024.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250324000268');
INSERT INTO reports (company_id, year, period, title, url) VALUES (18, 2025, 'Q2', '반기보고서 (2025.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250814001640');
INSERT INTO reports (company_id, year, period, title, url) VALUES (18, 2025, 'Q3', '분기보고서 (2025.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20251114000184');
INSERT INTO reports (company_id, year, period, title, url) VALUES (19, 2022, 'annual', '사업보고서 (2022.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20230323000659');
INSERT INTO reports (company_id, year, period, title, url) VALUES (19, 2023, 'annual', '사업보고서 (2023.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240319000814');
INSERT INTO reports (company_id, year, period, title, url) VALUES (19, 2023, 'Q1', '분기보고서 (2023.03)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20230515000690');
INSERT INTO reports (company_id, year, period, title, url) VALUES (19, 2023, 'Q2', '반기보고서 (2023.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20230814001308');
INSERT INTO reports (company_id, year, period, title, url) VALUES (19, 2023, 'Q3', '분기보고서 (2023.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20231114001356');
INSERT INTO reports (company_id, year, period, title, url) VALUES (19, 2024, 'annual', '사업보고서 (2024.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250320001165');
INSERT INTO reports (company_id, year, period, title, url) VALUES (19, 2024, 'Q1', '[기재정정]분기보고서 (2024.03)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240522000108');
INSERT INTO reports (company_id, year, period, title, url) VALUES (19, 2024, 'Q2', '반기보고서 (2024.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240814002123');
INSERT INTO reports (company_id, year, period, title, url) VALUES (19, 2024, 'Q3', '분기보고서 (2024.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20241114000021');
INSERT INTO reports (company_id, year, period, title, url) VALUES (19, 2025, 'Q1', '분기보고서 (2025.03)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250514000267');
INSERT INTO reports (company_id, year, period, title, url) VALUES (19, 2025, 'Q2', '반기보고서 (2025.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250814002310');
INSERT INTO reports (company_id, year, period, title, url) VALUES (19, 2025, 'Q3', '분기보고서 (2025.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20251114001002');
INSERT INTO reports (company_id, year, period, title, url) VALUES (20, 2024, 'annual', '사업보고서 (2024.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250317000468');
INSERT INTO reports (company_id, year, period, title, url) VALUES (20, 2024, 'Q2', '반기보고서 (2024.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240812000294');
INSERT INTO reports (company_id, year, period, title, url) VALUES (20, 2024, 'Q3', '분기보고서 (2024.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20241111000103');
INSERT INTO reports (company_id, year, period, title, url) VALUES (20, 2025, 'Q1', '분기보고서 (2025.03)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250515000107');
INSERT INTO reports (company_id, year, period, title, url) VALUES (20, 2025, 'Q2', '반기보고서 (2025.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250814001416');
INSERT INTO reports (company_id, year, period, title, url) VALUES (20, 2025, 'Q3', '분기보고서 (2025.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20251114002028');
INSERT INTO reports (company_id, year, period, title, url) VALUES (21, 2024, 'annual', '[기재정정]사업보고서 (2024.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250421000041');
INSERT INTO reports (company_id, year, period, title, url) VALUES (21, 2024, 'Q1', '[기재정정]분기보고서 (2024.03)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240827000048');
INSERT INTO reports (company_id, year, period, title, url) VALUES (21, 2024, 'Q2', '반기보고서 (2024.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240814003506');
INSERT INTO reports (company_id, year, period, title, url) VALUES (21, 2024, 'Q3', '분기보고서 (2024.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20241114002597');
INSERT INTO reports (company_id, year, period, title, url) VALUES (21, 2025, 'Q1', '분기보고서 (2025.03)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250515001080');
INSERT INTO reports (company_id, year, period, title, url) VALUES (21, 2025, 'Q2', '반기보고서 (2025.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250814004275');
INSERT INTO reports (company_id, year, period, title, url) VALUES (21, 2025, 'Q3', '분기보고서 (2025.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20251114003055');
INSERT INTO reports (company_id, year, period, title, url) VALUES (22, 2021, 'annual', '감사보고서 (2021.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20220711000625');
INSERT INTO reports (company_id, year, period, title, url) VALUES (22, 2022, 'annual', '감사보고서 (2022.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20230331001309');
INSERT INTO reports (company_id, year, period, title, url) VALUES (22, 2023, 'annual', '[기재정정]사업보고서 (2023.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240729000269');
INSERT INTO reports (company_id, year, period, title, url) VALUES (22, 2024, 'annual', '사업보고서 (2024.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250320001659');
INSERT INTO reports (company_id, year, period, title, url) VALUES (22, 2024, 'Q1', '분기보고서 (2024.03)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240514001228');
INSERT INTO reports (company_id, year, period, title, url) VALUES (22, 2024, 'Q2', '반기보고서 (2024.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240814001075');
INSERT INTO reports (company_id, year, period, title, url) VALUES (22, 2024, 'Q3', '분기보고서 (2024.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20241114002771');
INSERT INTO reports (company_id, year, period, title, url) VALUES (22, 2025, 'Q1', '분기보고서 (2025.03)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250515000966');
INSERT INTO reports (company_id, year, period, title, url) VALUES (22, 2025, 'Q2', '반기보고서 (2025.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250814003831');
INSERT INTO reports (company_id, year, period, title, url) VALUES (22, 2025, 'Q3', '분기보고서 (2025.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20251114001241');
INSERT INTO reports (company_id, year, period, title, url) VALUES (23, 2023, 'annual', '사업보고서 (2023.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240319000532');
INSERT INTO reports (company_id, year, period, title, url) VALUES (23, 2023, 'Q1', '분기보고서 (2023.03)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20230512000855');
INSERT INTO reports (company_id, year, period, title, url) VALUES (23, 2023, 'Q2', '반기보고서 (2023.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20230811002422');
INSERT INTO reports (company_id, year, period, title, url) VALUES (23, 2023, 'Q3', '분기보고서 (2023.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20231110000472');
INSERT INTO reports (company_id, year, period, title, url) VALUES (23, 2024, 'annual', '사업보고서 (2024.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250318000779');
INSERT INTO reports (company_id, year, period, title, url) VALUES (23, 2024, 'Q1', '분기보고서 (2024.03)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240513000515');
INSERT INTO reports (company_id, year, period, title, url) VALUES (23, 2024, 'Q2', '반기보고서 (2024.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240813001337');
INSERT INTO reports (company_id, year, period, title, url) VALUES (23, 2024, 'Q3', '분기보고서 (2024.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20241112000009');
INSERT INTO reports (company_id, year, period, title, url) VALUES (23, 2025, 'Q1', '분기보고서 (2025.03)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250513000499');
INSERT INTO reports (company_id, year, period, title, url) VALUES (23, 2025, 'Q2', '반기보고서 (2025.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250813001443');
INSERT INTO reports (company_id, year, period, title, url) VALUES (23, 2025, 'Q3', '분기보고서 (2025.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20251110000330');
INSERT INTO reports (company_id, year, period, title, url) VALUES (25, 2021, 'annual', '연결감사보고서 (2021.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20220328000495');
INSERT INTO reports (company_id, year, period, title, url) VALUES (25, 2022, 'annual', '연결감사보고서 (2022.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20230330001056');
INSERT INTO reports (company_id, year, period, title, url) VALUES (25, 2023, 'annual', '연결감사보고서 (2023.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240328000239');
INSERT INTO reports (company_id, year, period, title, url) VALUES (25, 2024, 'annual', '[기재정정]감사보고서 (2024.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250422000427');
INSERT INTO reports (company_id, year, period, title, url) VALUES (26, 2022, 'annual', '감사보고서 (2022.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20230404002725');
INSERT INTO reports (company_id, year, period, title, url) VALUES (26, 2023, 'annual', '감사보고서 (2023.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240409003188');
INSERT INTO reports (company_id, year, period, title, url) VALUES (26, 2024, 'annual', '감사보고서 (2024.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250404002720');
INSERT INTO reports (company_id, year, period, title, url) VALUES (27, 2021, 'annual', '감사보고서 (2021.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20220401000203');
INSERT INTO reports (company_id, year, period, title, url) VALUES (27, 2023, 'annual', '감사보고서 (2023.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240405003279');
INSERT INTO reports (company_id, year, period, title, url) VALUES (27, 2024, 'annual', '감사보고서 (2024.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250407002272');
INSERT INTO reports (company_id, year, period, title, url) VALUES (28, 2023, 'annual', '사업보고서 (2023.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240318000800');
INSERT INTO reports (company_id, year, period, title, url) VALUES (28, 2023, 'Q1', '분기보고서 (2023.03)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20230515002719');
INSERT INTO reports (company_id, year, period, title, url) VALUES (28, 2023, 'Q2', '반기보고서 (2023.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20230814002387');
INSERT INTO reports (company_id, year, period, title, url) VALUES (28, 2023, 'Q3', '분기보고서 (2023.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20231114000598');
INSERT INTO reports (company_id, year, period, title, url) VALUES (28, 2024, 'annual', '사업보고서 (2024.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250318001192');
INSERT INTO reports (company_id, year, period, title, url) VALUES (28, 2024, 'Q1', '분기보고서 (2024.03)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240514000947');
INSERT INTO reports (company_id, year, period, title, url) VALUES (28, 2024, 'Q2', '[기재정정]반기보고서 (2024.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240826000402');
INSERT INTO reports (company_id, year, period, title, url) VALUES (28, 2024, 'Q3', '분기보고서 (2024.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20241114000760');
INSERT INTO reports (company_id, year, period, title, url) VALUES (28, 2025, 'Q1', '분기보고서 (2025.03)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250515002944');
INSERT INTO reports (company_id, year, period, title, url) VALUES (28, 2025, 'Q2', '반기보고서 (2025.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250814001862');
INSERT INTO reports (company_id, year, period, title, url) VALUES (28, 2025, 'Q3', '분기보고서 (2025.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20251114001622');
INSERT INTO reports (company_id, year, period, title, url) VALUES (29, 2021, 'annual', '사업보고서 (2021.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20220317001170');
INSERT INTO reports (company_id, year, period, title, url) VALUES (29, 2021, 'Q1', '분기보고서 (2021.03)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20210514001535');
INSERT INTO reports (company_id, year, period, title, url) VALUES (29, 2021, 'Q2', '반기보고서 (2021.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20210817001983');
INSERT INTO reports (company_id, year, period, title, url) VALUES (29, 2021, 'Q3', '분기보고서 (2021.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20211115002018');
INSERT INTO reports (company_id, year, period, title, url) VALUES (29, 2022, 'annual', '사업보고서 (2022.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20230316001371');
INSERT INTO reports (company_id, year, period, title, url) VALUES (29, 2022, 'Q1', '분기보고서 (2022.03)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20220516001540');
INSERT INTO reports (company_id, year, period, title, url) VALUES (29, 2022, 'Q2', '반기보고서 (2022.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20220816002169');
INSERT INTO reports (company_id, year, period, title, url) VALUES (29, 2022, 'Q3', '분기보고서 (2022.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20221114002559');
INSERT INTO reports (company_id, year, period, title, url) VALUES (29, 2023, 'annual', '사업보고서 (2023.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240314001722');
INSERT INTO reports (company_id, year, period, title, url) VALUES (29, 2023, 'Q1', '분기보고서 (2023.03)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20230515002680');
INSERT INTO reports (company_id, year, period, title, url) VALUES (29, 2023, 'Q2', '반기보고서 (2023.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20230811002572');
INSERT INTO reports (company_id, year, period, title, url) VALUES (29, 2023, 'Q3', '분기보고서 (2023.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20231114002950');
INSERT INTO reports (company_id, year, period, title, url) VALUES (29, 2024, 'annual', '사업보고서 (2024.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250313001454');
INSERT INTO reports (company_id, year, period, title, url) VALUES (29, 2024, 'Q1', '분기보고서 (2024.03)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240516001882');
INSERT INTO reports (company_id, year, period, title, url) VALUES (29, 2024, 'Q2', '반기보고서 (2024.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240814004110');
INSERT INTO reports (company_id, year, period, title, url) VALUES (29, 2024, 'Q3', '분기보고서 (2024.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20241114001778');
INSERT INTO reports (company_id, year, period, title, url) VALUES (29, 2025, 'Q1', '분기보고서 (2025.03)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250515000170');
INSERT INTO reports (company_id, year, period, title, url) VALUES (29, 2025, 'Q2', '반기보고서 (2025.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250814003105');
INSERT INTO reports (company_id, year, period, title, url) VALUES (29, 2025, 'Q3', '분기보고서 (2025.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20251114002853');
INSERT INTO reports (company_id, year, period, title, url) VALUES (30, 2023, 'annual', '감사보고서 (2023.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240402003077');
INSERT INTO reports (company_id, year, period, title, url) VALUES (30, 2024, 'annual', '감사보고서 (2024.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250325000383');
INSERT INTO reports (company_id, year, period, title, url) VALUES (31, 2021, 'annual', '사업보고서 (2021.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20220331001656');
INSERT INTO reports (company_id, year, period, title, url) VALUES (31, 2021, 'Q1', '분기보고서 (2021.03)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20210514000600');
INSERT INTO reports (company_id, year, period, title, url) VALUES (31, 2021, 'Q2', '반기보고서 (2021.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20210812000522');
INSERT INTO reports (company_id, year, period, title, url) VALUES (31, 2021, 'Q3', '분기보고서 (2021.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20211115000816');
INSERT INTO reports (company_id, year, period, title, url) VALUES (31, 2022, 'annual', '사업보고서 (2022.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20230331002102');
INSERT INTO reports (company_id, year, period, title, url) VALUES (31, 2022, 'Q1', '분기보고서 (2022.03)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20220516000327');
INSERT INTO reports (company_id, year, period, title, url) VALUES (31, 2022, 'Q2', '반기보고서 (2022.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20220816001450');
INSERT INTO reports (company_id, year, period, title, url) VALUES (31, 2022, 'Q3', '분기보고서 (2022.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20221114002614');
INSERT INTO reports (company_id, year, period, title, url) VALUES (31, 2023, 'annual', '사업보고서 (2023.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240325000516');
INSERT INTO reports (company_id, year, period, title, url) VALUES (31, 2023, 'Q1', '분기보고서 (2023.03)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20230515002610');
INSERT INTO reports (company_id, year, period, title, url) VALUES (31, 2023, 'Q2', '반기보고서 (2023.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20230811002605');
INSERT INTO reports (company_id, year, period, title, url) VALUES (31, 2023, 'Q3', '분기보고서 (2023.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20231114002791');
INSERT INTO reports (company_id, year, period, title, url) VALUES (31, 2024, 'annual', '사업보고서 (2024.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250325000852');
INSERT INTO reports (company_id, year, period, title, url) VALUES (31, 2024, 'Q1', '분기보고서 (2024.03)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240516000883');
INSERT INTO reports (company_id, year, period, title, url) VALUES (31, 2024, 'Q2', '반기보고서 (2024.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240814001149');
INSERT INTO reports (company_id, year, period, title, url) VALUES (31, 2024, 'Q3', '분기보고서 (2024.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20241114000690');
INSERT INTO reports (company_id, year, period, title, url) VALUES (31, 2025, 'Q1', '분기보고서 (2025.03)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250515002172');
INSERT INTO reports (company_id, year, period, title, url) VALUES (31, 2025, 'Q2', '반기보고서 (2025.06)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250814002377');
INSERT INTO reports (company_id, year, period, title, url) VALUES (31, 2025, 'Q3', '분기보고서 (2025.09)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20251113000902');
INSERT INTO reports (company_id, year, period, title, url) VALUES (32, 2021, 'annual', '감사보고서 (2021.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20220331003261');
INSERT INTO reports (company_id, year, period, title, url) VALUES (32, 2022, 'annual', '감사보고서 (2022.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20230331002939');
INSERT INTO reports (company_id, year, period, title, url) VALUES (32, 2023, 'annual', '감사보고서 (2023.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240401001287');
INSERT INTO reports (company_id, year, period, title, url) VALUES (32, 2024, 'annual', '감사보고서 (2024.12)', 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250402001474');
