const fs = require('fs');
const path = require('path');

// 1. Read the JSON data
const jsonPath = path.join(__dirname, '../web/src/data/financial_data.json');
const rawData = fs.readFileSync(jsonPath, 'utf8');
const financialData = JSON.parse(rawData);

// 2. Define the static company list to get IDs (Same as initial migration)
const COMPANY_IDS = {
    '한스바이오메드': 1, 'HansBiomed': 1,
    '엘앤씨바이오': 2, 'L&C Bio': 2,
    '제테마': 3, 'Jetema': 3,
    '한국비엔씨': 4, 'BNC Korea': 4,
    '종근당바이오': 5, 'Chong Kun Dang Bio': 5,
    '휴온스': 6, 'Huons': 6,
    '휴온스글로벌': 7, 'Huons Global': 7,
    '휴메딕스': 8, 'Humedix': 8,
    '휴젤': 9, 'Hugel': 9,
    '메디톡스': 10, 'Medytox': 10,
    '대웅제약': 11, 'Daewoong Pharma': 11,
    '파마리서치': 12, 'PharmaResearch': 12,
    '클래시스': 13, 'Classys': 13,
    '케어젠': 14, 'Caregen': 14,
    '원텍': 15, 'Wontech': 15,
    '동방메디컬': 16, 'Dongbang Medical': 16,
    '제이시스메디칼': 17, 'Jeisys Medical': 17,
    '바이오비쥬': 18, 'BioBijou': 18,
    '바이오플러스': 19, 'BioPlus': 19,
    '비올': 20, 'Viol': 20,
    '하이로닉': 21, 'Hironic': 21,
    '레이저옵텍': 22, 'Laseroptek': 22,
    '유바이오로직스': 23, 'EuBiologics': 23,
    '바임글로벌': 24, 'Vaim Global': 24,
    '엑소코바이오': 25, 'ExoCoBio': 25,
    '알에프바이오': 26, 'RFBio': 26,
    '차메디텍': 27, 'Cha Meditech': 27,
    'JW중외제약': 28, 'JW Pharmaceutical': 28,
    '동국제약': 29, 'Dongkook Pharmaceutical': 29,
    '리젠바이오텍': 30, 'Regen Biotech': 30,
    '울트라브이': 31, 'Ultra V': 31,
    '제노스': 32, 'Genoss': 32,
    '멀츠': 33, 'Merz Aesthetics': 33,
    '앨러간': 34, 'Allergan Aesthetics': 34,
    '갈더마': 35, 'Galderma': 35,
    '테옥산': 36, 'Teoxane': 36
};

function escapeSql(str) {
    if (!str) return 'NULL';
    return `'${str.replace(/'/g, "''")}'`;
}

function parseBigInt(val) {
    if (!val || val === 'N/A' || val === '-') return 'NULL';
    // Remove commas if any (though example JSON didn't show them, safe to be sure)
    const clean = String(val).replace(/,/g, '');
    const parsed = parseInt(clean, 10);
    return isNaN(parsed) ? 'NULL' : parsed;
}

let sql = `-- Migration: Add financials and reports tables, and populate data

-- 1. Add columns to companies
ALTER TABLE companies ADD COLUMN IF NOT EXISTS stock_code text;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS logo_url text;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS website_url text;

-- 2. Create financials table
CREATE TABLE IF NOT EXISTS financials (
  id bigint generated by default as identity primary key,
  company_id bigint references companies(id) not null,
  year int not null,
  revenue bigint,
  operating_profit bigint,
  rd_cost text, -- Keeping as text for 'N/A' or mixed values if needed, or stick to structure
  data_type text, -- 'annual', 'annual_naver', etc.
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint unique_financial_year unique (company_id, year)
);

-- 3. Create reports table
CREATE TABLE IF NOT EXISTS reports (
  id bigint generated by default as identity primary key,
  company_id bigint references companies(id) not null,
  year int not null,
  period text not null, -- 'annual', '1Q', '2Q', '3Q', '4Q'
  title text not null,
  url text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Enable RLS
ALTER TABLE financials ENABLE ROW LEVEL SECURITY;
ALTER TABLE reports ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  DROP POLICY "Enable read for all" ON financials;
EXCEPTION WHEN undefined_object THEN END $$;
CREATE POLICY "Enable read for all" ON financials FOR SELECT USING (true);

DO $$ BEGIN
  DROP POLICY "Enable read for all" ON reports;
EXCEPTION WHEN undefined_object THEN END $$;
CREATE POLICY "Enable read for all" ON reports FOR SELECT USING (true);

-- 5. Data Migration
`;

// Helper arrays
const companyUpdates = [];
const financialInserts = [];
const reportInserts = [];

Object.entries(financialData).forEach(([nameKo, data]) => {
    const companyId = COMPANY_IDS[nameKo];
    if (!companyId) return; // Skip if unknown company

    // Update Company Info
    const stockCode = data.stock_code || null;
    const summary = data.company_summary || null;
    if (stockCode || summary) {
        companyUpdates.push(`UPDATE companies SET stock_code = ${escapeSql(stockCode)}, description = ${escapeSql(summary)} WHERE id = ${companyId};`);
    }

    // Financial History
    if (data.financial_history) {
        Object.entries(data.financial_history).forEach(([yearStr, yearData]) => {
            const year = parseInt(yearStr, 10);

            // Financials
            const revenue = parseBigInt(yearData.revenue);
            const opProfit = parseBigInt(yearData.operating_profit);
            const rdCost = escapeSql(yearData.rd_cost);
            const dataType = escapeSql(yearData.data_type || 'annual');

            // Use INSERT ON CONFLICT to avoid accumulation if run multiple times
            if (revenue !== 'NULL' || opProfit !== 'NULL') {
                financialInserts.push(`
          INSERT INTO financials (company_id, year, revenue, operating_profit, rd_cost, data_type)
          VALUES (${companyId}, ${year}, ${revenue}, ${opProfit}, ${rdCost}, ${dataType})
          ON CONFLICT (company_id, year) DO UPDATE SET
            revenue = EXCLUDED.revenue,
            operating_profit = EXCLUDED.operating_profit,
            rd_cost = EXCLUDED.rd_cost,
            data_type = EXCLUDED.data_type;
          `);
            }

            // Reports
            // Annual
            if (yearData.annual_report && yearData.annual_report.link) {
                reportInserts.push(`INSERT INTO reports (company_id, year, period, title, url) VALUES (${companyId}, ${year}, 'annual', ${escapeSql(yearData.annual_report.title)}, ${escapeSql(yearData.annual_report.link)});`);
            }
            // Quarters
            ['Q1', 'Q2', 'Q3', 'Q4'].forEach(q => {
                if (yearData[q] && yearData[q].link) {
                    reportInserts.push(`INSERT INTO reports (company_id, year, period, title, url) VALUES (${companyId}, ${year}, '${q}', ${escapeSql(yearData[q].title)}, ${escapeSql(yearData[q].link)});`);
                }
            });
        });
    }
});

sql += `
-- Update Companies
${companyUpdates.join('\n')}

-- Insert Financials
${financialInserts.join('\n')}

-- Insert Reports
-- For reports, we don't have a unique constraint easily (title/url duplicates?), so we might delete existing first for Idempotency
DELETE FROM reports;
${reportInserts.join('\n')}
`;

fs.writeFileSync(path.join(__dirname, '../supabase/migrations/20260218130000_migrate_all_data.sql'), sql);
console.log('Migration file generated.');
