-- MFDS (식약처) 의료기기 품목허가 + 품목정보 통합 테이블
-- 두 API(품목허가/품목정보) 데이터를 허가번호로 매칭하여 저장

create table if not exists mfds_products (
    id bigint generated by default as identity primary key,
    permit_number text not null unique,              -- 정규화된 허가번호 (공백제거, e.g. 제허17-203호)
    permit_number_raw text,                          -- API 원본 형식
    company_id bigint references companies(id),      -- FK → companies (제테마=3)
    company_name text not null,                      -- 업체명 (e.g. 제테마)
    product_category text,                           -- 품목명 (e.g. 조직수복용생체재료)
    permit_date text,                                -- 허가일자 YYYYMMDD
    status text not null default 'active',           -- active / cancelled
    cancel_date text,                                -- 취소일자
    brand_names text,                                -- PRDT_NM_INFO (브랜드명 목록)
    model_info text,                                 -- TYPE_INFO (모델 정보)
    model_count int,                                 -- 모델 수
    oem_client text,                                 -- MNFT_CLNT_NM (OEM 위탁자)
    manufacturer text,                               -- MNSC_NM (제조원)
    manufacturer_country text,                       -- MNSC_NATN_CD
    device_grade text,                               -- 등급
    classification_no text,                          -- 품목분류번호 (e.g. B04230.01)
    industry_type text,                              -- INDT_NM (제조업/수입업)
    use_purpose text,                                -- USE_PURPS_CONT
    raw_permit_json jsonb,                           -- 품목허가 API 원본
    raw_product_json jsonb,                          -- 품목정보 API 원본
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

-- Indexes
create index if not exists idx_mfds_products_company_id on mfds_products(company_id);
create index if not exists idx_mfds_products_company_name on mfds_products(company_name);
create index if not exists idx_mfds_products_status on mfds_products(status);
create index if not exists idx_mfds_products_category on mfds_products(product_category);

-- updated_at trigger
create or replace function set_mfds_products_updated_at()
returns trigger as $$
begin
    new.updated_at = timezone('utc'::text, now());
    return new;
end;
$$ language plpgsql;

drop trigger if exists trg_mfds_products_updated_at on mfds_products;
create trigger trg_mfds_products_updated_at
before update on mfds_products
for each row
execute function set_mfds_products_updated_at();

-- RLS: read-only for all
alter table mfds_products enable row level security;

do $$
begin
    drop policy "Enable read access for all users" on mfds_products;
exception
    when undefined_object then null;
end $$;

create policy "Enable read access for all users" on mfds_products
for select using (true);
